name: Test

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

      - name: Prepare config JSONs
        run: |
          # echo '{"solana-foundation/anchor":{}}' > repo.json
          wget https://github.com/os-checker/os-checker-action/raw/refs/heads/main/test.json -O repo.json

      - uses: os-checker/os-checker-action@HEAD
        with:
          configs: repo.json
          database_repo: os-checker/test-database
          base_url: /os-checker-action/
          docs_url: https://os-checker.github.io/os-checker-action/docs
          gh_token: ${{ secrets.GH_TOKEN }}

      - run: df -alh && tree -h -L 4 /tmp/check

      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/check/dist

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: run

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
