name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Prepare config JSONs
        run: |
          echo '{"os-checker/os-checker-test-suite":{}}' > repo.json

      - uses: os-checker/os-checker-action@v0.0.12
        with:
          configs: repo.json
          database_repo: os-checker/test-database
          base_url: /os-checker-action/
          docs_url: https://os-checker.github.io/os-checker-action/docs

